module ApiMessage
  # 2xx Success
  SUCCESS = 200
  CREATED = 201
  NO_CONTENT = 204

  # 4xx Client Error
  ERROR_CODE_BAD_REQUEST = 400
  ERROR_CODE_MISSING_PARAMETER = ERROR_CODE_BAD_REQUEST
  ERROR_CODE_INVALID_PARAMETER = ERROR_CODE_BAD_REQUEST
  ERROR_CODE_PERMISSION_DENIED = 401
  ERROR_CODE_RECORD_NOT_FOUND = ERROR_CODE_BAD_REQUEST
  ERROR_CODE_FORBIDDEN = 403 # Authenticated but not authorized
  ERROR_CODE_UNPROCESSABLE_ENTITY = 422
  ERROR_CODE_TOO_MANY_REQUESTS = 429

  # 5xx Server Error
  ERROR_CODE_INTERNAL_SERVER_ERROR = 500
end
